version: '3.6'
services:
  # database
  postgres:
    image: mdillon/postgis:11
    hostname: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=testingwithrentals
    ports:
      # we can still access the database from outside the docker network
      - "5434:5432"
    volumes:
      - ./sql-init.sql:/docker-entrypoint-initdb.d/sql-init.sql

  # application
  rentals:
    build: .
    hostname: rentals
    restart: always
    environment:
      # wait for postgres to come up (internal port on docker network)
      - WAIT_HOSTS=postgres:5432
      # wait for 2 seconds after connecting before running the application
      - WAIT_AFTER=2
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=testingwithrentals
    ports:
      - "8080:8080"
